### ISSUE TITLE
Help to configure 

### ISSUE THREAD

**Issue by reactiver001** [cierra2016/candy-machine-v2-bot#1]
The first great work in this project 

I try run but have this error: 

candy-machine-v2-bot>node index.js
file:///C:/Users/Administrator/Desktop/candy-machine-v2-bot/connection.js:140
    slot = confirmation?.slot || 0;
                        ^

SyntaxError: Unexpected token '.'
[90m    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)[39m

Thanks for all

**Comment by cierra2016** [comment]
Thanks for your question

**Comment by reactiver001** [comment]
Hello , update now but have the same problem.

**Comment by cierra2016** [comment]
That error comes from connection.
I push changed index.js file with RPC connection.
Please retry again

**Comment by reactiver001** [comment]
Hello , 
Yes i think is problem in connection RPC now work. What i need change for use my wallet ? only need change .env? 
thanks

**Comment by cierra2016** [comment]
Yes only need to change the .env file.

**Comment by reactiver001** [comment]
I think now work , you have any email or discord for talk to you better.
thanks

**Comment by cierra2016** [comment]
supernftier#5786 
DM me on discord
